version: 2.1

parameters:
  secrethub_org:
    type: string
    default: "gravitee-lab"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  heroku: circleci/heroku@1.2.3
  docker: circleci/docker@1.5
  secrethub: secrethub/cli@1.0.0
jobs:
  container_images_publish:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    environment:
      SECRETHUB_ORG: << pipeline.parameters.secrethub_org >>
      SECRETHUB_REPO: << pipeline.parameters.secrethub_repo >>
    steps:
      - checkout
      - secrethub/install
      - docker/install-docker-compose
      - run:
          command: |
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
          name: "Container images build: Hugo Build (checking no hugo build error occurs)"
      - run:
          command: |
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
          name: "Container images publish to quay.io"

  deploy_to_heroku:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    environment:
      SECRETHUB_ORG: << pipeline.parameters.secrethub_org >>
      SECRETHUB_REPO: << pipeline.parameters.secrethub_repo >>
      HEROKU_APP_ID: ric-carl
    steps:
      - checkout
      - secrethub/install
      - heroku/install
      - run:
          command: |
            echo "Checking context variables from [riccarl-cicd] context"
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
            echo "HEROKU_APP_ID=[${HEROKU_APP_ID}]"
          name: "Deploy to heroku as https://ric-carl.herokuapp.com/ "
      - run:
          name: "Heroku Check Authentication:"
          command: |
            echo "Checking Heroku Authentication is successful, with the secrethub provided Heroku API Token"
            export HEROKU_API_TOKEN=$(secrethub read "${SECRETHUB_ORG}/${SECRETHUB_REPO}/ccccc")
            heroku auth:whoami
      - run:
          name: "Deploy to Heroku via Git, website at https://ric-carl.herokuapp.com/ "
          command: |
            echo "Deploying to Heroku, via git, Deployment defined in the Heroku.yml"
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
            echo "HEROKU_APP_ID=[${HEROKU_APP_ID}]"
            export REPO_HEROKU=https://heroku:${HEROKU_API_TOKEN}@git.heroku.com/${HEROKU_APP_ID}.git
            git remote add heroku ${REPO_HEROKU}
            git push -u heroku master
            echo "Run this to see the logs of the Heroku deployment: "
            echo "heroku logs --tail --app ${HEROKU_APP_ID}"
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - container_images_publish:
          context: riccarl-cicd
      - deploy_to_heroku:
          context: riccarl-cicd
          requires:
            - build_and_publish
